const TEXT_TYPE_DEFAULT = 'TEXT_TYPE_DEFAULT'
const TEXT_TYPE_EMAIL = 'TEXT_TYPE_EMAIL'
const TEXT_TYPE_PHONE = 'TEXT_TYPE_PHONE'
const TEXT_TYPE_ZIP_CODE = 'TEXT_TYPE_ZIP_CODE'

const TYPES = [
  TEXT_TYPE_DEFAULT,
  TEXT_TYPE_EMAIL,
  TEXT_TYPE_PHONE,
  TEXT_TYPE_ZIP_CODE,
]

export default TYPES
