const LABEL_TYPE_1 = 'LABEL_TYPE_1'
const LABEL_TYPE_2 = 'LABEL_TYPE_2'
const LABEL_TYPE_3 = 'LABEL_TYPE_3'
const LABEL_TYPE_4 = 'LABEL_TYPE_4'
const LABEL_TYPE_5 = 'LABEL_TYPE_5'
const LABEL_TYPE_6 = 'LABEL_TYPE_6'
const LABEL_TYPE_7 = 'LABEL_TYPE_7'
const LABEL_TYPE_8 = 'LABEL_TYPE_8'
const LABEL_TYPE_9 = 'LABEL_TYPE_9'
const LABEL_TYPE_10 = 'LABEL_TYPE_10'
const LABEL_TYPE_11 = 'LABEL_TYPE_11'
const LABEL_TYPE_12 = 'LABEL_TYPE_12'

const TYPES = [
  LABEL_TYPE_1,
  LABEL_TYPE_2,
  LABEL_TYPE_3,
  LABEL_TYPE_4,
  LABEL_TYPE_5,
  LABEL_TYPE_6,
  LABEL_TYPE_7,
  LABEL_TYPE_8,
  LABEL_TYPE_9,
  LABEL_TYPE_10,
  LABEL_TYPE_11,
  LABEL_TYPE_12,
]

export default TYPES
