const BUTTON_TYPE_1 = 'BUTTON_TYPE_1'
const BUTTON_TYPE_2 = 'BUTTON_TYPE_2'
const BUTTON_TYPE_3 = 'BUTTON_TYPE_3'
const BUTTON_TYPE_4 = 'BUTTON_TYPE_4'
const BUTTON_TYPE_5 = 'BUTTON_TYPE_5'
const BUTTON_TYPE_6 = 'BUTTON_TYPE_6'
const BUTTON_TYPE_7 = 'BUTTON_TYPE_7'
const BUTTON_TYPE_8 = 'BUTTON_TYPE_8'
const BUTTON_TYPE_9 = 'BUTTON_TYPE_9'
const BUTTON_TYPE_10 = 'BUTTON_TYPE_10'
const BUTTON_TYPE_11 = 'BUTTON_TYPE_11'
const BUTTON_TYPE_12 = 'BUTTON_TYPE_12'

const TYPES = [
  BUTTON_TYPE_1,
  BUTTON_TYPE_2,
  BUTTON_TYPE_3,
  BUTTON_TYPE_4,
  BUTTON_TYPE_5,
  BUTTON_TYPE_6,
  BUTTON_TYPE_7,
  BUTTON_TYPE_8,
  BUTTON_TYPE_9,
  BUTTON_TYPE_10,
  BUTTON_TYPE_11,
  BUTTON_TYPE_12,
]

export default TYPES
